import type { AppData } from "@/features/finance/ledger";

export const seedData: AppData = {
  organization: {
    id: "org-1",
    name: "CONSTRUPROYECT S.R.L.",
  },
  currentUser: {
    id: "user-admin",
    name: "Mariela Acosta",
    role: "admin",
  },
  categories: [
    { id: "cat-compra-solar", name: "COMPRA SOLAR", sortOrder: 1, isActive: true },
    { id: "cat-permisologia", name: "PERMISOLOGIA", sortOrder: 2, isActive: true },
    { id: "cat-diseno", name: "DISEÑO", sortOrder: 3, isActive: true },
    { id: "cat-solar", name: "SOLAR", sortOrder: 4, isActive: true },
    { id: "cat-hormigon-armado", name: "HORMIGON ARMADO", sortOrder: 5, isActive: true },
    { id: "cat-costos-indirectos", name: "COSTOS INDIRECTOS", sortOrder: 6, isActive: true },
    { id: "cat-escalera", name: "ESCALERA", sortOrder: 7, isActive: true },
    { id: "cat-sheetrock", name: "SHEETROCK", sortOrder: 8, isActive: true },
    { id: "cat-electricidad", name: "ELECTRICIDAD", sortOrder: 9, isActive: true },
    { id: "cat-plomeria", name: "PLOMERIA", sortOrder: 10, isActive: true },
    { id: "cat-pintura", name: "PINTURA", sortOrder: 11, isActive: true },
    { id: "cat-terminaciones", name: "TERMINACIONES", sortOrder: 12, isActive: true },
    { id: "cat-miscelaneo", name: "MISCELANEO", sortOrder: 13, isActive: true },
  ],
  subcategories: [
    // COMPRA SOLAR
    { id: "sub-separacion", categoryId: "cat-compra-solar", name: "SEPARACION", sortOrder: 1, isActive: true },
    { id: "sub-tazacion", categoryId: "cat-compra-solar", name: "TAZACION", sortOrder: 2, isActive: true },
    { id: "sub-inicial", categoryId: "cat-compra-solar", name: "INICIAL", sortOrder: 3, isActive: true },
    { id: "sub-prestamo", categoryId: "cat-compra-solar", name: "PRESTAMO", sortOrder: 4, isActive: true },
    { id: "sub-cuotas-mensual", categoryId: "cat-compra-solar", name: "CUOTAS MENSUAL", sortOrder: 5, isActive: true },
    // PERMISOLOGIA
    { id: "sub-carta-no-objecion", categoryId: "cat-permisologia", name: "CARTA NO OBJECION", sortOrder: 1, isActive: true },
    { id: "sub-pago-carta", categoryId: "cat-permisologia", name: "PAGO CARTA", sortOrder: 2, isActive: true },
    { id: "sub-imp-ayuntamiento", categoryId: "cat-permisologia", name: "IMP. AYUNTAMIENTO", sortOrder: 3, isActive: true },
    { id: "sub-imp-codia", categoryId: "cat-permisologia", name: "IMP CODIA", sortOrder: 4, isActive: true },
    { id: "sub-imp-obras-publica", categoryId: "cat-permisologia", name: "IMP OBRAS PUBLICA", sortOrder: 5, isActive: true },
    { id: "sub-edenorte", categoryId: "cat-permisologia", name: "EDENORTE", sortOrder: 6, isActive: true },
    { id: "sub-coraazan", categoryId: "cat-permisologia", name: "CORAAZAN", sortOrder: 7, isActive: true },
    { id: "sub-medio-ambiente", categoryId: "cat-permisologia", name: "MEDIO AMBIENTE", sortOrder: 8, isActive: true },
    { id: "sub-estudio-suelo", categoryId: "cat-permisologia", name: "ESTUDIO DE SUELO", sortOrder: 9, isActive: true },
    // DISEÑO
    { id: "sub-diseno-arq", categoryId: "cat-diseno", name: "DISEÑO ARQ.", sortOrder: 1, isActive: true },
    { id: "sub-calculo-estructura", categoryId: "cat-diseno", name: "CALCULO ESTRUCTURA", sortOrder: 2, isActive: true },
    { id: "sub-calculo-electrico", categoryId: "cat-diseno", name: "CALCULO ELECTRICO", sortOrder: 3, isActive: true },
    { id: "sub-calculo-sanitario", categoryId: "cat-diseno", name: "CALCULO SANITARIO", sortOrder: 4, isActive: true },
    { id: "sub-render", categoryId: "cat-diseno", name: "RENDER", sortOrder: 5, isActive: true },
    { id: "sub-diseno-climatico", categoryId: "cat-diseno", name: "DISEÑO CLIMATICO", sortOrder: 6, isActive: true },
    { id: "sub-ruta-evacuacion", categoryId: "cat-diseno", name: "RUTA DE EVACUACION", sortOrder: 7, isActive: true },
    { id: "sub-presupuesto", categoryId: "cat-diseno", name: "PRESUPUESTO", sortOrder: 8, isActive: true },
    // SOLAR
    { id: "sub-movimiento-tierra", categoryId: "cat-solar", name: "MOVIMIENTO DE TIERRA", sortOrder: 1, isActive: true },
    { id: "sub-topografo", categoryId: "cat-solar", name: "TOPOGRAFO", sortOrder: 2, isActive: true },
    { id: "sub-cisterna", categoryId: "cat-solar", name: "CISTERNA", sortOrder: 3, isActive: true },
    { id: "sub-relleno", categoryId: "cat-solar", name: "RELLENO", sortOrder: 4, isActive: true },
    { id: "sub-cierre-solar", categoryId: "cat-solar", name: "CIERRE SOLAR", sortOrder: 5, isActive: true },
    { id: "sub-caseta-materiales", categoryId: "cat-solar", name: "CASETA DE MATERIALES", sortOrder: 6, isActive: true },
    { id: "sub-bote", categoryId: "cat-solar", name: "BOTE", sortOrder: 7, isActive: true },
    { id: "sub-limpieza-terreno", categoryId: "cat-solar", name: "LIMPIEZA TERRENO Y BASURA", sortOrder: 8, isActive: true },
    { id: "sub-verja-laterales", categoryId: "cat-solar", name: "VERJA LATERALES", sortOrder: 9, isActive: true },
    // HORMIGON ARMADO
    { id: "sub-sanja-relleno", categoryId: "cat-hormigon-armado", name: "SANJA Y RELLENO", sortOrder: 1, isActive: true },
    { id: "sub-zapatas-columnas-mat", categoryId: "cat-hormigon-armado", name: "ZAPATAS Y COLUMNAS MATERIALES", sortOrder: 2, isActive: true },
    { id: "sub-muros-materiales", categoryId: "cat-hormigon-armado", name: "MUROS MATERIALES", sortOrder: 3, isActive: true },
    { id: "sub-materiales-losa", categoryId: "cat-hormigon-armado", name: "MATERIALES LOSA", sortOrder: 4, isActive: true },
    { id: "sub-chapapote-mat", categoryId: "cat-hormigon-armado", name: "CHAPAPOTE MATERIALES", sortOrder: 5, isActive: true },
    { id: "sub-empanete-mat", categoryId: "cat-hormigon-armado", name: "EMPAÑETE MATERIALES", sortOrder: 6, isActive: true },
    { id: "sub-mdo-varilla", categoryId: "cat-hormigon-armado", name: "MDO. VARILLA HASTA 1 N", sortOrder: 7, isActive: true },
    { id: "sub-mdo-encofrado", categoryId: "cat-hormigon-armado", name: "MDO. ENCOFRADO", sortOrder: 8, isActive: true },
    { id: "sub-mdo-losa", categoryId: "cat-hormigon-armado", name: "MDO LOSA", sortOrder: 9, isActive: true },
    { id: "sub-mdo-muros", categoryId: "cat-hormigon-armado", name: "MDO. MUROS", sortOrder: 10, isActive: true },
    { id: "sub-mdo-empanete", categoryId: "cat-hormigon-armado", name: "MDO. EMPAÑETE", sortOrder: 11, isActive: true },
    { id: "sub-mdo-chapapote", categoryId: "cat-hormigon-armado", name: "MDO. CHAPAPOTE", sortOrder: 12, isActive: true },
    // COSTOS INDIRECTOS
    { id: "sub-direccion-tecnica", categoryId: "cat-costos-indirectos", name: "DIRECCION TECNICA", sortOrder: 1, isActive: true },
    { id: "sub-gasto-administrativo", categoryId: "cat-costos-indirectos", name: "GASTO ADMINISTRATIVO", sortOrder: 2, isActive: true },
    { id: "sub-transporte", categoryId: "cat-costos-indirectos", name: "TRANSPORTE", sortOrder: 3, isActive: true },
    { id: "sub-seguros-fianzas", categoryId: "cat-costos-indirectos", name: "SEGUROS Y FIANZAS", sortOrder: 4, isActive: true },
    { id: "sub-fondo-pension", categoryId: "cat-costos-indirectos", name: "FONDO DE PENSION", sortOrder: 5, isActive: true },
    { id: "sub-personal-fijo", categoryId: "cat-costos-indirectos", name: "PERSONAL FIJO EN OBRA", sortOrder: 6, isActive: true },
    { id: "sub-gasto-oficina", categoryId: "cat-costos-indirectos", name: "GASTO OFICINA", sortOrder: 7, isActive: true },
    { id: "sub-telefono", categoryId: "cat-costos-indirectos", name: "TELEFONO", sortOrder: 8, isActive: true },
    { id: "sub-iguala-contable", categoryId: "cat-costos-indirectos", name: "IGUALA CONTABLE", sortOrder: 9, isActive: true },
    { id: "sub-imprevisto", categoryId: "cat-costos-indirectos", name: "IMPREVISTO", sortOrder: 10, isActive: true },
    // ELECTRICIDAD
    { id: "sub-electricidad-mat", categoryId: "cat-electricidad", name: "MATERIALES ELECTRICOS", sortOrder: 1, isActive: true },
    { id: "sub-electricidad-mdo", categoryId: "cat-electricidad", name: "M.D.O. ELECTRICISTA", sortOrder: 2, isActive: true },
    // PLOMERIA
    { id: "sub-plomeria-mat", categoryId: "cat-plomeria", name: "MATERIALES DE PLOMERIA", sortOrder: 1, isActive: true },
    { id: "sub-plomeria-mdo", categoryId: "cat-plomeria", name: "M.D.O. PLOMERO", sortOrder: 2, isActive: true },
    // PINTURA
    { id: "sub-pintura-interior", categoryId: "cat-pintura", name: "PINTURA INTERIOR", sortOrder: 1, isActive: true },
    { id: "sub-pintura-exterior", categoryId: "cat-pintura", name: "PINTURA EXTERIOR", sortOrder: 2, isActive: true },
    // TERMINACIONES
    { id: "sub-piso", categoryId: "cat-terminaciones", name: "PISO", sortOrder: 1, isActive: true },
    { id: "sub-revestimiento", categoryId: "cat-terminaciones", name: "REVESTIMIENTO", sortOrder: 2, isActive: true },
    { id: "sub-puertas", categoryId: "cat-terminaciones", name: "PUERTAS", sortOrder: 3, isActive: true },
    { id: "sub-ventanas", categoryId: "cat-terminaciones", name: "VENTANAS", sortOrder: 4, isActive: true },
    { id: "sub-fino-techo", categoryId: "cat-terminaciones", name: "FINO DE TECHO", sortOrder: 5, isActive: true },
    { id: "sub-impermeabilizante", categoryId: "cat-terminaciones", name: "IMPERMEABILIZANTE", sortOrder: 6, isActive: true },
  ],
  projects: [
    {
      id: "project-plaza-tigaiga",
      name: "Plaza Tigaiga",
      clientName: "Tigaiga",
      location: "Santiago, RD",
      status: "active",
      startDate: "2025-07-01",
      endDate: null,
      notes: "Construcción de oficinas comerciales - 2 niveles.",
    },
  ],
  budgetVersions: [
    {
      id: "budget-plaza-approved",
      projectId: "project-plaza-tigaiga",
      versionName: "Análisis de Costo Base",
      status: "approved",
      isLocked: true,
      approvedAt: "2025-12-28T09:00:00.000Z",
    },
  ],
  budgetSections: [
    {
      id: "section-preliminares",
      budgetVersionId: "budget-plaza-approved",
      code: "A",
      name: "TRABAJOS PRELIMINARES Y BAJO NIVEL DE PISO",
      costType: "direct",
      sortOrder: 1,
    },
    {
      id: "section-hormigon",
      budgetVersionId: "budget-plaza-approved",
      code: "B",
      name: "HORMIGON ARMADO",
      costType: "direct",
      sortOrder: 2,
    },
    {
      id: "section-terminaciones",
      budgetVersionId: "budget-plaza-approved",
      code: "C",
      name: "TERMINACIONES Y ACABADOS",
      costType: "direct",
      sortOrder: 3,
    },
    {
      id: "section-instalaciones",
      budgetVersionId: "budget-plaza-approved",
      code: "D",
      name: "INSTALACIONES",
      costType: "direct",
      sortOrder: 4,
    },
    {
      id: "section-indirectos",
      budgetVersionId: "budget-plaza-approved",
      code: "II",
      name: "COSTOS INDIRECTOS",
      costType: "indirect",
      sortOrder: 5,
    },
  ],
  budgetLines: [
    // A - TRABAJOS PRELIMINARES
    {
      id: "bl-corte", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-preliminares", categoryId: "cat-solar", subcategoryId: "sub-movimiento-tierra",
      phase: null, area: null, lineCode: "1.01",
      description: "Corte y carga capa vegetal 0.20m", quantity: 231, unit: "M2", unitPrice: 160.60,
      totalBudgeted: 37099, notes: "", sortOrder: 1, isManualTotal: false,
    },
    {
      id: "bl-charrancha", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-preliminares", categoryId: "cat-solar", subcategoryId: "sub-topografo",
      phase: null, area: null, lineCode: "1.02",
      description: "Charrancha y replanteo", quantity: 231, unit: "M2", unitPrice: 235.60,
      totalBudgeted: 54424, notes: "", sortOrder: 2, isManualTotal: false,
    },
    {
      id: "bl-excavaciones", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-preliminares", categoryId: "cat-hormigon-armado", subcategoryId: "sub-sanja-relleno",
      phase: null, area: null, lineCode: "2.01",
      description: "Excavaciones de fundaciones compresor", quantity: 55.55, unit: "M3", unitPrice: 3099.93,
      totalBudgeted: 172201, notes: "", sortOrder: 3, isManualTotal: false,
    },
    {
      id: "bl-bote-material", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-preliminares", categoryId: "cat-solar", subcategoryId: "sub-bote",
      phase: null, area: null, lineCode: "2.02",
      description: "Carga y bote de material sobrante excav.", quantity: 115.32, unit: "M3E", unitPrice: 317.95,
      totalBudgeted: 36665, notes: "", sortOrder: 4, isManualTotal: false,
    },
    {
      id: "bl-relleno-fund", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-preliminares", categoryId: "cat-solar", subcategoryId: "sub-relleno",
      phase: null, area: null, lineCode: "2.03",
      description: "Relleno de reposición en fundaciones", quantity: 40.66, unit: "M3C", unitPrice: 1678.45,
      totalBudgeted: 68247, notes: "", sortOrder: 5, isManualTotal: false,
    },
    // B - HORMIGON ARMADO
    {
      id: "bl-zapatas", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-hormigon", categoryId: "cat-hormigon-armado", subcategoryId: "sub-zapatas-columnas-mat",
      phase: null, area: null, lineCode: "3.01",
      description: "Zapatas aisladas Z1, Z2, Z3", quantity: 7.05, unit: "M3", unitPrice: 14854,
      totalBudgeted: 104753, notes: "", sortOrder: 6, isManualTotal: false,
    },
    {
      id: "bl-columnas", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-hormigon", categoryId: "cat-hormigon-armado", subcategoryId: "sub-zapatas-columnas-mat",
      phase: null, area: null, lineCode: "3.06",
      description: "Columnas C1 y C2", quantity: 1, unit: "PA", unitPrice: 85000,
      totalBudgeted: 85000, notes: "", sortOrder: 7, isManualTotal: true,
    },
    {
      id: "bl-muros", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-hormigon", categoryId: "cat-hormigon-armado", subcategoryId: "sub-muros-materiales",
      phase: null, area: null, lineCode: "3.08",
      description: "Muros de 8\" con bastones", quantity: 1, unit: "PA", unitPrice: 120000,
      totalBudgeted: 120000, notes: "", sortOrder: 8, isManualTotal: true,
    },
    {
      id: "bl-losa", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-hormigon", categoryId: "cat-hormigon-armado", subcategoryId: "sub-materiales-losa",
      phase: null, area: null, lineCode: "3.10",
      description: "Losa estructural maciza 0.12m", quantity: 1, unit: "PA", unitPrice: 250000,
      totalBudgeted: 250000, notes: "", sortOrder: 9, isManualTotal: true,
    },
    // C - TERMINACIONES
    {
      id: "bl-piso", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-terminaciones", categoryId: "cat-terminaciones", subcategoryId: "sub-piso",
      phase: null, area: null, lineCode: "C.01",
      description: "Pisos porcelanato", quantity: 231, unit: "M2", unitPrice: 850,
      totalBudgeted: 196350, notes: "", sortOrder: 10, isManualTotal: false,
    },
    {
      id: "bl-pintura-ext", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-terminaciones", categoryId: "cat-pintura", subcategoryId: "sub-pintura-exterior",
      phase: null, area: null, lineCode: "C.02",
      description: "Pintura acrilica exterior", quantity: 1, unit: "PA", unitPrice: 95000,
      totalBudgeted: 95000, notes: "", sortOrder: 11, isManualTotal: true,
    },
    // D - INSTALACIONES
    {
      id: "bl-plomeria-mat", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-instalaciones", categoryId: "cat-plomeria", subcategoryId: "sub-plomeria-mat",
      phase: null, area: null, lineCode: "D.01",
      description: "Materiales de plomería", quantity: 1, unit: "PA", unitPrice: 52000,
      totalBudgeted: 52000, notes: "", sortOrder: 12, isManualTotal: true,
    },
    {
      id: "bl-plomeria-mdo", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-instalaciones", categoryId: "cat-plomeria", subcategoryId: "sub-plomeria-mdo",
      phase: null, area: null, lineCode: "D.02",
      description: "M.D.O. Plomero", quantity: 1, unit: "PA", unitPrice: 65000,
      totalBudgeted: 65000, notes: "", sortOrder: 13, isManualTotal: true,
    },
    {
      id: "bl-electr-mat", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-instalaciones", categoryId: "cat-electricidad", subcategoryId: "sub-electricidad-mat",
      phase: null, area: null, lineCode: "D.03",
      description: "Materiales eléctricos", quantity: 1, unit: "PA", unitPrice: 85000,
      totalBudgeted: 85000, notes: "", sortOrder: 14, isManualTotal: true,
    },
    {
      id: "bl-electr-mdo", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-instalaciones", categoryId: "cat-electricidad", subcategoryId: "sub-electricidad-mdo",
      phase: null, area: null, lineCode: "D.04",
      description: "M.D.O. Electricista", quantity: 1, unit: "PA", unitPrice: 82000,
      totalBudgeted: 82000, notes: "", sortOrder: 15, isManualTotal: true,
    },
    // II - COSTOS INDIRECTOS
    {
      id: "bl-dir-tecnica", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-indirectos", categoryId: "cat-costos-indirectos", subcategoryId: "sub-direccion-tecnica",
      phase: null, area: null, lineCode: "II.01",
      description: "Dirección técnica y responsabilidad", quantity: 1, unit: "PA", unitPrice: 913914,
      totalBudgeted: 913914, notes: "12% de costos directos", sortOrder: 16, isManualTotal: true,
    },
    {
      id: "bl-gasto-admin", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-indirectos", categoryId: "cat-costos-indirectos", subcategoryId: "sub-gasto-administrativo",
      phase: null, area: null, lineCode: "II.02",
      description: "Gastos administrativos", quantity: 1, unit: "PA", unitPrice: 190399,
      totalBudgeted: 190399, notes: "2.5% de costos directos", sortOrder: 17, isManualTotal: true,
    },
    {
      id: "bl-transporte", budgetVersionId: "budget-plaza-approved", projectId: "project-plaza-tigaiga",
      sectionId: "section-indirectos", categoryId: "cat-costos-indirectos", subcategoryId: "sub-transporte",
      phase: null, area: null, lineCode: "II.03",
      description: "Transporte", quantity: 1, unit: "PA", unitPrice: 152319,
      totalBudgeted: 152319, notes: "2% de costos directos", sortOrder: 18, isManualTotal: true,
    },
  ],
  contractors: [
    {
      id: "contractor-ariel",
      fullName: "Maestro Ariel",
      trade: "Albañilería",
      phone: "",
      email: "",
      notes: "Maestro principal de obra",
      isActive: true,
    },
    {
      id: "contractor-plomero",
      fullName: "Plomero Juan",
      trade: "Plomería",
      phone: "809-555-0101",
      email: "",
      notes: "",
      isActive: true,
    },
    {
      id: "contractor-electricista",
      fullName: "Carlos Electricidad",
      trade: "Electricidad",
      phone: "809-555-0102",
      email: "",
      notes: "",
      isActive: true,
    },
  ],
  contractorContracts: [
    {
      id: "contract-ariel-plaza",
      projectId: "project-plaza-tigaiga",
      contractorId: "contractor-ariel",
      categoryId: "cat-hormigon-armado",
      subcategoryId: "sub-sanja-relleno",
      scopeDescription: "Obra gris — cimentación, muros, losa",
      agreedTotal: 500000,
      status: "active",
      startDate: "2026-01-14",
      endDate: null,
      notes: "Pagos parciales por avances (nominas)",
    },
    {
      id: "contract-plomero-plaza",
      projectId: "project-plaza-tigaiga",
      contractorId: "contractor-plomero",
      categoryId: "cat-plomeria",
      subcategoryId: "sub-plomeria-mdo",
      scopeDescription: "Instalación de plomería completa",
      agreedTotal: 65000,
      status: "active",
      startDate: "2026-03-14",
      endDate: null,
      notes: "",
    },
    {
      id: "contract-electricista-plaza",
      projectId: "project-plaza-tigaiga",
      contractorId: "contractor-electricista",
      categoryId: "cat-electricidad",
      subcategoryId: "sub-electricidad-mdo",
      scopeDescription: "Canalización eléctrica",
      agreedTotal: 82000,
      status: "active",
      startDate: "2026-03-14",
      endDate: null,
      notes: "",
    },
  ],
  transactions: [
    // --- INGRESOS (Desembolsos del cliente) ---
    {
      id: "txn-income-1", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: null, subcategoryId: null, transactionType: "income",
      transactionDate: "2025-07-01", amount: 120000,
      detail: "Desembolso inicial — planos", payeeOrSource: "Cliente Tigaiga",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-income-2", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: null, subcategoryId: null, transactionType: "income",
      transactionDate: "2025-11-21", amount: 144700,
      detail: "Desembolso — estudio de suelo, imp. ayunt.", payeeOrSource: "Cliente Tigaiga",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-income-3", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: null, subcategoryId: null, transactionType: "income",
      transactionDate: "2026-01-06", amount: 2000000,
      detail: "Avance 1 — DEPOSITO BANRESERVA", payeeOrSource: "Cliente Tigaiga",
      paymentMethod: "depósito bancario", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-income-4", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: null, subcategoryId: null, transactionType: "income",
      transactionDate: "2026-03-12", amount: 2000000,
      detail: "Avance 2 — DEPOSITO SANTA CRUZ", payeeOrSource: "Cliente Tigaiga",
      paymentMethod: "depósito bancario", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    // --- GASTOS ---
    {
      id: "txn-exp-1", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-permisologia", subcategoryId: "sub-carta-no-objecion", transactionType: "expense",
      transactionDate: "2025-07-14", amount: 1000,
      detail: "PAGO CARTA", payeeOrSource: "MOPC",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-2", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-diseno", subcategoryId: "sub-diseno-arq", transactionType: "expense",
      transactionDate: "2025-07-19", amount: 100000,
      detail: "AVANCE diseño arquitectónico", payeeOrSource: "Ana María",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-3", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-permisologia", subcategoryId: "sub-pago-carta", transactionType: "expense",
      transactionDate: "2025-08-12", amount: 25000,
      detail: "PAGO CARTA NO OBJECCION", payeeOrSource: "MOPC",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-4", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-diseno", subcategoryId: "sub-calculo-sanitario", transactionType: "expense",
      transactionDate: "2025-09-15", amount: 25000,
      detail: "AVANCE cálculo sanitario", payeeOrSource: "Ingeniero",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-5", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-permisologia", subcategoryId: "sub-imp-ayuntamiento", transactionType: "expense",
      transactionDate: "2026-01-09", amount: 40700,
      detail: "PAGO IMPUESTO AYUNTAMIENTO", payeeOrSource: "Ayuntamiento Santiago",
      paymentMethod: "tarjeta", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-6", projectId: "project-plaza-tigaiga", budgetLineId: "bl-corte",
      categoryId: "cat-solar", subcategoryId: "sub-movimiento-tierra", transactionType: "expense",
      transactionDate: "2026-01-14", amount: 37500,
      detail: "CORTE", payeeOrSource: "Maquinista",
      paymentMethod: "efectivo", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-7", projectId: "project-plaza-tigaiga", budgetLineId: "bl-bote-material",
      categoryId: "cat-solar", subcategoryId: "sub-bote", transactionType: "expense",
      transactionDate: "2026-01-14", amount: 85500,
      detail: "BOTE de material", payeeOrSource: "Camiones",
      paymentMethod: "efectivo", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-8", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-solar", subcategoryId: "sub-cisterna", transactionType: "expense",
      transactionDate: "2026-01-14", amount: 69485,
      detail: "MATERIALES FERRETERIA DORADO", payeeOrSource: "Ferretería Dorado",
      paymentMethod: "tarjeta", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-9", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-costos-indirectos", subcategoryId: "sub-gasto-administrativo", transactionType: "expense",
      transactionDate: "2026-01-08", amount: 140000,
      detail: "Gasto administrativo enero", payeeOrSource: "Oficina",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-10", projectId: "project-plaza-tigaiga", budgetLineId: null,
      categoryId: "cat-costos-indirectos", subcategoryId: "sub-personal-fijo", transactionType: "expense",
      transactionDate: "2026-01-08", amount: 100000,
      detail: "Personal en obra enero", payeeOrSource: "Nómina",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-11", projectId: "project-plaza-tigaiga", budgetLineId: "bl-zapatas",
      categoryId: "cat-hormigon-armado", subcategoryId: "sub-zapatas-columnas-mat", transactionType: "expense",
      transactionDate: "2026-02-12", amount: 198000,
      detail: "VARILLA Y CEMENTO", payeeOrSource: "Ferretería Dorado",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-12", projectId: "project-plaza-tigaiga", budgetLineId: "bl-muros",
      categoryId: "cat-hormigon-armado", subcategoryId: "sub-muros-materiales", transactionType: "expense",
      transactionDate: "2026-02-12", amount: 22303,
      detail: "400 BLOCK DE 8", payeeOrSource: "Bloquera",
      paymentMethod: "efectivo", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-13", projectId: "project-plaza-tigaiga", budgetLineId: "bl-losa",
      categoryId: "cat-hormigon-armado", subcategoryId: "sub-materiales-losa", transactionType: "expense",
      transactionDate: "2026-03-25", amount: 107871,
      detail: "VARILLAS para losa", payeeOrSource: "Ferretería Dorado",
      paymentMethod: "transferencia", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-14", projectId: "project-plaza-tigaiga", budgetLineId: "bl-plomeria-mat",
      categoryId: "cat-plomeria", subcategoryId: "sub-plomeria-mat", transactionType: "expense",
      transactionDate: "2026-03-14", amount: 25275,
      detail: "MATERIALES plomería", payeeOrSource: "Ferretería Central",
      paymentMethod: "efectivo", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
    {
      id: "txn-exp-15", projectId: "project-plaza-tigaiga", budgetLineId: "bl-electr-mat",
      categoryId: "cat-electricidad", subcategoryId: "sub-electricidad-mat", transactionType: "expense",
      transactionDate: "2026-03-14", amount: 10730,
      detail: "MATERIALES eléctricos", payeeOrSource: "Electrical Supply",
      paymentMethod: "tarjeta", externalReference: "", contractorContractId: null,
      createdBy: "user-admin", receiptPath: null, deletedAt: null,
    },
  ],
  contractorPayments: [
    {
      id: "cp-ariel-1",
      contractorContractId: "contract-ariel-plaza",
      transactionId: "txn-exp-6",
      paymentDate: "2026-01-14",
      amount: 37500,
      notes: "Avance 1 — corte terreno",
    },
  ],
  suggestionOptions: [
    { id: "sug-cp-1", kind: "counterparty", value: "Cliente Tigaiga", normalizedValue: "cliente tigaiga", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-cp-2", kind: "counterparty", value: "Ferretería Dorado", normalizedValue: "ferretería dorado", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-cp-3", kind: "counterparty", value: "Ferretería Central", normalizedValue: "ferretería central", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-cp-4", kind: "counterparty", value: "Ayuntamiento Santiago", normalizedValue: "ayuntamiento santiago", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-pm-1", kind: "payment_method", value: "transferencia", normalizedValue: "transferencia", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-pm-2", kind: "payment_method", value: "efectivo", normalizedValue: "efectivo", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-pm-3", kind: "payment_method", value: "cheque", normalizedValue: "cheque", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-pm-4", kind: "payment_method", value: "tarjeta", normalizedValue: "tarjeta", createdAt: "2025-07-01T09:00:00.000Z" },
    { id: "sug-pm-5", kind: "payment_method", value: "depósito bancario", normalizedValue: "depósito bancario", createdAt: "2025-07-01T09:00:00.000Z" },
  ],
  invoices: [],
};

/**
 * Returns the seed to use on first launch.
 *
 * When `CONTROL_CENTRAL_BLANK_SEED=1` is set (used by the packaged desktop
 * app shipped to clients), we keep the chart of accounts (categories,
 * subcategories, suggestion options) but drop all demo transactional data so
 * the client starts from a clean slate.
 */
export function getInitialSeed(): AppData {
  if (process.env.CONTROL_CENTRAL_BLANK_SEED === "1") {
    return {
      ...seedData,
      projects: [],
      budgetVersions: [],
      budgetLines: [],
      contractors: [],
      contractorContracts: [],
      transactions: [],
      contractorPayments: [],
      invoices: [],
    };
  }
  return seedData;
}
